# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    ".venv",
    "__pycache__",
    "*conda*",
    "**/TODO/kitty"
]
cache-dir = "~/.cache/ruff"
line-length = 100
indent-width = 4
target-version = "py312"
# Tespect gitignore
respect-gitignore = true
fix-only = true
# Enumerate all fixed violations.
show-fixes = true
extend-include = ["*.ipynb", "*.pyx"]

src = ["src", "fsutils", "hwutils","termllama", "graphs", "narration", "pyimagesearch"]

[format]

# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# def test(
#     a,
#     b,
# ): pass

# # Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code blokcs in docstrings. Supports Md, rST
docstring-code-format = true

# # Set the line length limit used when formatting code snippets in
# # docstrings.
# #
# # This only has an effect when the `docstring-code-format` setting is
# # enabled.
docstring-code-line-length = "dynamic"

[lint]
select = ["E", "F", "C", 'W', "B", "UP", "D107", "D104","D301","D401","D400","ANN201", "ANN206", "S103", "S105", "S112", "S110", "A", "EXE", "PIE", "RET", "SIM", "PLR", "PLW", "RUF", "PTH","D406","FBT","PERF","D212"] # 'D' Django, 'ANN' annotations, 'S' built-ins, 'A', 'EXE', 'PIE', 'RET', 'SIM', 'PLR', 'PLW', 'RUF' ruff-lint ,'C' codesmell, 'E' convention, 'F' error, 'B' bug, 'UP' unused variables, 'W' warning.

fixable = ['ALL']

ignore = ["E501", "N999", "N806", "FBT002", 'D417', 'E501', 'E303'] #"D211", "D213", "W1514", "E701" E702]
#   ---------------------------------------------------------------
#   - E501: Line too long
#   - E701: Multiple statements on one line
#   - E702: Multiple lines ending with different indentation levels
#   - C: Too complex
#   ----------------------------------------------------------------
#   - N999: Invalid name (no description)
#   - N806: Name should be uppercase (deprecated)
#   ----------------------------------------------------------------

extend-fixable = ["B", "D","ANN201",  "RET504", "EXE", "ANN", 'SIM108', 'SIM115', 'SIM117', 'SIM105', "PERF", "PTH","RUF","E"]
# Disable fix for unused imports (`F401`) and unused variables (`F841`) in tests.
unfixable = ["F401", 'F841']

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"


# Comments starting with these tags will be ignored by commented-out code detection
task-tags = ["TODO", "FIXME", "XXX", "- [ ]", "[ ]", "- [x]", "[x]", "NOTE"]

[lint.extend-per-file-ignores]
"__init__.py" = ["E402"]

[lint.flake8-annotations]
allow-star-arg-any = false

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.flake8-import-conventions.aliases]
# # Declare the default aliases.
altair = "alt"
"matplotlib.pyplot" = "plt"
numpy = "np"
pandas = "pd"
seaborn = "sns"
scipy = "sp"

[lint.flake8-quotes]
docstring-quotes = "double"
multiline-quotes = "double"

[lint.isort]
extra-standard-library = ["path", "pandas"]
force-wrap-aliases = true
combine-as-imports = true

[lint.pycodestyle]
max-line-length = 100 # E501 reports lines that exceed the length of 100.

# [lint.pydocstyle]
# convention = "google"  # Accepts: "google", "numpy", or "pep257".


# Lint Reference:
# --------------
# Pyflakes              (F)
# Pycodestyle           (E, W)
# Mccabe                (C90)
# Isort                 (I)
# Pep8-naming           (N)
# Pydocstyle            (D)
# Pyupgrade             (UP)
# flake8-2020           (YTT)
# flake8-annotations    (ANN)
# flake8-async          (ASYNC)



# Enumerate all fixed violations.
# fix-only = true
# show-fixes = true
# show-source = true
